# Generated by Django 2.0.5 on 2018-05-26 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codigo', models.CharField(db_column='mrcCodigo', max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='gruNombre', max_length=25)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='gruEstado', max_length=1)),
            ],
            options={
                'db_table': 'inv_grupos',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('codigo', models.CharField(db_column='itmCodigo', max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='itmNombre', max_length=25)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='itmEstado', max_length=1)),
                ('usuarioCreacion', models.CharField(db_column='itmUsrCreacion', max_length=10)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, db_column='itmFecCreacion')),
                ('usuarioModificacion', models.CharField(db_column='itmUsrModificacion', max_length=10)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_column='itmFecModificacion')),
                ('grupo', models.ForeignKey(blank=True, db_column='gruCodigo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Grupo')),
            ],
            options={
                'db_table': 'inv_items',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codigo', models.CharField(db_column='mrcCodigo', max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='mrcNombre', max_length=25)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='mrcEstado', max_length=1)),
            ],
            options={
                'db_table': 'inv_marcas',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.ForeignKey(blank=True, db_column='mrcCodigo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Marca'),
        ),
    ]
