# Generated by Django 2.0.5 on 2018-05-31 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPrecios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecVigencia', models.DateTimeField(db_column='itmPreFecVigencia')),
                ('precio', models.DecimalField(db_column='itmPrecio', decimal_places=2, max_digits=9)),
                ('usuarioModificacion', models.CharField(db_column='itmUsrModificacion', max_length=10)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, db_column='itmFecModificacion')),
                ('item', models.ForeignKey(db_column='itmCodigo', on_delete=django.db.models.deletion.CASCADE, to='inventario.Item')),
            ],
            options={
                'db_table': 'inv_items_precios',
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemprecios',
            unique_together={('item', 'fecVigencia')},
        ),
    ]
