# Generated by Django 2.0.5 on 2018-06-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20180531_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='itemprecios',
            name='fechaModificacion',
        ),
        migrations.RemoveField(
            model_name='itemprecios',
            name='usuarioModificacion',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='codigo',
        ),
        migrations.AddField(
            model_name='grupo',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True, db_column='gruFecCreacion'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fechaModificacion',
            field=models.DateTimeField(auto_now=True, db_column='gruFecModificacion'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='id',
            field=models.AutoField(db_column='gruId', default='0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuarioCreacion',
            field=models.CharField(db_column='gruUsrCreacion', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuarioModificacion',
            field=models.CharField(db_column='gruUsrModificacion', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.AutoField(db_column='itmId', default='0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='itemprecios',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True, db_column='itmPreFecModificacion'),
        ),
        migrations.AddField(
            model_name='itemprecios',
            name='usuarioCreacion',
            field=models.CharField(db_column='itmPreUsrModificacion', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='marca',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True, db_column='mrcFecCreacion'),
        ),
        migrations.AddField(
            model_name='marca',
            name='fechaModificacion',
            field=models.DateTimeField(auto_now=True, db_column='mrcFecModificacion'),
        ),
        migrations.AddField(
            model_name='marca',
            name='id',
            field=models.AutoField(db_column='mrcId', default='0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='marca',
            name='usuarioCreacion',
            field=models.CharField(db_column='mrcUsrCreacion', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='marca',
            name='usuarioModificacion',
            field=models.CharField(db_column='mrcUsrModificacion', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.CharField(db_column='itmCodigo', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True, db_column='itmFecCreacion'),
        ),
        migrations.AlterField(
            model_name='item',
            name='grupo',
            field=models.ForeignKey(blank=True, db_column='gruId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Grupo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='marca',
            field=models.ForeignKey(blank=True, db_column='mrcId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Marca'),
        ),
        migrations.AlterField(
            model_name='itemprecios',
            name='item',
            field=models.ForeignKey(db_column='itmId', on_delete=django.db.models.deletion.CASCADE, to='inventario.Item'),
        ),
        migrations.AlterField(
            model_name='itemprecios',
            name='precio',
            field=models.DecimalField(db_column='itmPreValor', decimal_places=2, max_digits=9),
        ),
    ]
