# Generated by Django 2.0.5 on 2018-06-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20180608_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='id',
            field=models.AutoField(db_column='mrcId', editable=False, primary_key=True, serialize=False),
        ),
    ]
