# Generated by Django 2.0.5 on 2018-06-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20180608_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='id',
            field=models.AutoField(db_column='gruId', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(db_column='itmId', editable=False, primary_key=True, serialize=False),
        ),
    ]
