# Generated by Django 2.0.5 on 2018-06-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20180610_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='dtm_fecha_creacion',
            field=models.DateTimeField(db_column='gruFecCreacion'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='dtm_fecha_modificacion',
            field=models.DateTimeField(db_column='gruFecModificacion'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dtm_fecha_creacion',
            field=models.DateTimeField(db_column='itmFecCreacion'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dtm_fecha_modificacion',
            field=models.DateTimeField(db_column='itmFecModificacion'),
        ),
        migrations.AlterField(
            model_name='itemprecios',
            name='dtm_fecha_creacion',
            field=models.DateTimeField(db_column='itmPreFecCreacion'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='dtm_fecha_creacion',
            field=models.DateTimeField(db_column='mrcFecCreacion'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='dtm_fecha_modificacion',
            field=models.DateTimeField(db_column='mrcFecModificacion'),
        ),
    ]
