# Generated by Django 2.0.5 on 2018-06-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20180610_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dtm_fecha_creacion',
            field=models.DateTimeField(db_column='itmFecCreacion', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='dtm_fecha_modificacion',
            field=models.DateTimeField(db_column='itmFecModificacion', null=True),
        ),
        migrations.AlterField(
            model_name='itemprecios',
            name='dtm_fecha_creacion',
            field=models.DateTimeField(db_column='itmPreFecCreacion', null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='dtm_fecha_creacion',
            field=models.DateTimeField(db_column='mrcFecCreacion', null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='dtm_fecha_modificacion',
            field=models.DateTimeField(db_column='mrcFecModificacion', null=True),
        ),
    ]
